export const jobData = [
  {
    id: 1,
    jobTitle: "Frontend Developer",
    companyName: "TechSolutions India",
    experience: "2-5 years",
    location: "Bangalore, Karnataka",
    jobDescription: "We are looking for a skilled Frontend Developer to join our team. You will be responsible for building user interfaces and implementing design systems.",
    jobSkills: ["React", "JavaScript", "HTML5", "CSS3", "Redux"],
    numberOfOpenings: 3,
    workMode: "hybrid",
    salary: "₹6,00,000 - ₹10,00,000 per year",
    datePosted: "2023-05-15"
  },
  {
    id: 2,
    jobTitle: "Backend Developer",
    companyName: "DataSystems Pvt Ltd",
    experience: "3-6 years",
    location: "Pune, Maharashtra",
    jobDescription: "Looking for a Backend Developer to design and implement scalable server-side applications and APIs.",
    jobSkills: ["Node.js", "Python", "MongoDB", "AWS", "REST APIs"],
    numberOfOpenings: 2,
    workMode: "wfo",
    salary: "₹8,00,000 - ₹12,00,000 per year",
    datePosted: "2023-05-18"
  },
  {
    id: 3,
    jobTitle: "Full Stack Developer",
    companyName: "WebCraft Technologies",
    experience: "4-7 years",
    location: "Hyderabad, Telangana",
    jobDescription: "Seeking a Full Stack Developer proficient in both frontend and backend technologies to build complete web applications.",
    jobSkills: ["JavaScript", "React", "Node.js", "Express", "SQL"],
    numberOfOpenings: 4,
    workMode: "remote",
    salary: "₹10,00,000 - ₹15,00,000 per year",
    datePosted: "2023-05-20"
  },
  {
    id: 4,
    jobTitle: "Data Scientist",
    companyName: "AnalyticsPro India",
    experience: "5-8 years",
    location: "Bangalore, Karnataka",
    jobDescription: "We need a Data Scientist to analyze complex data and build machine learning models to solve business problems.",
    jobSkills: ["Python", "Machine Learning", "TensorFlow", "Pandas", "SQL"],
    numberOfOpenings: 1,
    workMode: "hybrid",
    salary: "₹12,00,000 - ₹18,00,000 per year",
    datePosted: "2023-05-22"
  },
  {
    id: 5,
    jobTitle: "DevOps Engineer",
    companyName: "CloudNova Solutions",
    experience: "3-6 years",
    location: "Chennai, Tamil Nadu",
    jobDescription: "Looking for a DevOps Engineer to implement CI/CD pipelines and manage cloud infrastructure.",
    jobSkills: ["AWS", "Docker", "Kubernetes", "Jenkins", "Terraform"],
    numberOfOpenings: 2,
    workMode: "wfo",
    salary: "₹9,00,000 - ₹14,00,000 per year",
    datePosted: "2023-05-25"
  },
  {
    id: 6,
    jobTitle: "UI/UX Designer",
    companyName: "DesignHub India",
    experience: "2-4 years",
    location: "Mumbai, Maharashtra",
    jobDescription: "Seeking a creative UI/UX Designer to design intuitive user interfaces and improve user experience.",
    jobSkills: ["Figma", "Adobe XD", "User Research", "Wireframing", "Prototyping"],
    numberOfOpenings: 3,
    workMode: "hybrid",
    salary: "₹5,00,000 - ₹8,00,000 per year",
    datePosted: "2023-05-28"
  },
  {
    id: 7,
    jobTitle: "Mobile App Developer",
    companyName: "AppInnovate",
    experience: "3-5 years",
    location: "Delhi",
    jobDescription: "Looking for a Mobile App Developer to build and maintain cross-platform mobile applications.",
    jobSkills: ["React Native", "Flutter", "JavaScript", "Redux", "Firebase"],
    numberOfOpenings: 2,
    workMode: "remote",
    salary: "₹7,00,000 - ₹11,00,000 per year",
    datePosted: "2023-06-01"
  },
  {
    id: 8,
    jobTitle: "QA Engineer",
    companyName: "QualityAssure Labs",
    experience: "2-4 years",
    location: "Bangalore, Karnataka",
    jobDescription: "We need a QA Engineer to develop test cases and ensure software quality through manual and automated testing.",
    jobSkills: ["Selenium", "JIRA", "Test Automation", "Manual Testing", "Postman"],
    numberOfOpenings: 2,
    workMode: "wfo",
    salary: "₹5,00,000 - ₹8,00,000 per year",
    datePosted: "2023-06-03"
  },
  {
    id: 9,
    jobTitle: "Product Manager",
    companyName: "ProductLynx",
    experience: "6-9 years",
    location: "Gurgaon, Haryana",
    jobDescription: "Seeking an experienced Product Manager to lead product development and strategy.",
    jobSkills: ["Product Strategy", "Agile", "Market Research", "Roadmapping", "Stakeholder Management"],
    numberOfOpenings: 1,
    workMode: "hybrid",
    salary: "₹15,00,000 - ₹22,00,000 per year",
    datePosted: "2023-06-05"
  },
  {
    id: 10,
    jobTitle: "Cloud Architect",
    companyName: "SkyCloud Technologies",
    experience: "8-10 years",
    location: "Pune, Maharashtra",
    jobDescription: "Looking for a Cloud Architect to design and implement cloud solutions for enterprise clients.",
    jobSkills: ["AWS", "Azure", "Cloud Security", "Microservices", "DevOps"],
    numberOfOpenings: 1,
    workMode: "wfo",
    salary: "₹18,00,000 - ₹25,00,000 per year",
    datePosted: "2023-06-08"
  },
  {
    id: 11,
    jobTitle: "Java Developer",
    companyName: "JavaWorks India",
    experience: "3-6 years",
    location: "Chennai, Tamil Nadu",
    jobDescription: "We need a Java Developer to build high-performance backend systems and applications.",
    jobSkills: ["Java", "Spring Boot", "Hibernate", "REST APIs", "Microservices"],
    numberOfOpenings: 3,
    workMode: "hybrid",
    salary: "₹8,00,000 - ₹12,00,000 per year",
    datePosted: "2023-06-10"
  },
  {
    id: 12,
    jobTitle: "Digital Marketing Specialist",
    companyName: "MarketGrow Digital",
    experience: "2-4 years",
    location: "Mumbai, Maharashtra",
    jobDescription: "Looking for a Digital Marketing Specialist to manage online campaigns and improve brand visibility.",
    jobSkills: ["SEO", "Social Media", "Google Ads", "Content Marketing", "Analytics"],
    numberOfOpenings: 2,
    workMode: "remote",
    salary: "₹4,00,000 - ₹7,00,000 per year",
    datePosted: "2023-06-12"
  },
  {
    id: 13,
    jobTitle: "Cybersecurity Analyst",
    companyName: "SecureNet India",
    experience: "4-7 years",
    location: "Bangalore, Karnataka",
    jobDescription: "Seeking a Cybersecurity Analyst to protect systems and networks from security threats.",
    jobSkills: ["Network Security", "Ethical Hacking", "SIEM", "Penetration Testing", "Firewalls"],
    numberOfOpenings: 1,
    workMode: "wfo",
    salary: "₹10,00,000 - ₹15,00,000 per year",
    datePosted: "2023-06-15"
  },
  {
    id: 14,
    jobTitle: "Content Writer",
    companyName: "ContentCraft Studios",
    experience: "1-3 years",
    location: "Delhi",
    jobDescription: "Looking for a creative Content Writer to produce engaging content for websites and marketing materials.",
    jobSkills: ["Content Writing", "SEO", "Blogging", "Copywriting", "Research"],
    numberOfOpenings: 2,
    workMode: "remote",
    salary: "₹3,00,000 - ₹5,00,000 per year",
    datePosted: "2023-06-18"
  },
  {
    id: 15,
    jobTitle: "HR Manager",
    companyName: "TalentFirst HR Solutions",
    experience: "5-8 years",
    location: "Hyderabad, Telangana",
    jobDescription: "We need an HR Manager to oversee recruitment, employee relations, and HR policies.",
    jobSkills: ["Recruitment", "Employee Engagement", "HR Policies", "Performance Management", "Compensation"],
    numberOfOpenings: 1,
    workMode: "wfo",
    salary: "₹9,00,000 - ₹12,00,000 per year",
    datePosted: "2023-06-20"
  },
  {
    id: 16,
    jobTitle: "Business Analyst",
    companyName: "BizAnalytix Consulting",
    experience: "3-5 years",
    location: "Gurgaon, Haryana",
    jobDescription: "Looking for a Business Analyst to analyze business processes and recommend improvements.",
    jobSkills: ["Requirements Gathering", "Data Analysis", "SQL", "Process Mapping", "Stakeholder Management"],
    numberOfOpenings: 2,
    workMode: "hybrid",
    salary: "₹7,00,000 - ₹10,00,000 per year",
    datePosted: "2023-06-22"
  },
  {
    id: 17,
    jobTitle: "AI/ML Engineer",
    companyName: "AI Innovations India",
    experience: "4-6 years",
    location: "Bangalore, Karnataka",
    jobDescription: "Seeking an AI/ML Engineer to develop and implement machine learning models.",
    jobSkills: ["Python", "TensorFlow", "PyTorch", "NLP", "Computer Vision"],
    numberOfOpenings: 2,
    workMode: "wfo",
    salary: "₹12,00,000 - ₹16,00,000 per year",
    datePosted: "2023-06-25"
  },
  {
    id: 18,
    jobTitle: "Sales Executive",
    companyName: "SalesForce India",
    experience: "2-4 years",
    location: "Mumbai, Maharashtra",
    jobDescription: "Looking for a Sales Executive to drive sales and build client relationships.",
    jobSkills: ["Sales", "Negotiation", "CRM", "Client Acquisition", "Communication"],
    numberOfOpenings: 3,
    workMode: "wfo",
    salary: "₹4,00,000 - ₹6,00,000 per year + incentives",
    datePosted: "2023-06-28"
  },
  {
    id: 19,
    jobTitle: "Database Administrator",
    companyName: "DataManage Systems",
    experience: "5-7 years",
    location: "Pune, Maharashtra",
    jobDescription: "We need a Database Administrator to manage and optimize database systems.",
    jobSkills: ["SQL", "MySQL", "PostgreSQL", "Database Security", "Performance Tuning"],
    numberOfOpenings: 1,
    workMode: "hybrid",
    salary: "₹10,00,000 - ₹14,00,000 per year",
    datePosted: "2023-07-01"
  },
  {
    id: 20,
    jobTitle: "Network Engineer",
    companyName: "NetConnect Solutions",
    experience: "3-5 years",
    location: "Chennai, Tamil Nadu",
    jobDescription: "Looking for a Network Engineer to design and maintain network infrastructure.",
    jobSkills: ["Cisco", "Routing", "Switching", "Firewalls", "Network Security"],
    numberOfOpenings: 2,
    workMode: "wfo",
    salary: "₹7,00,000 - ₹10,00,000 per year",
    datePosted: "2023-07-03"
  },
  {
    id: 21,
    jobTitle: "Technical Support Engineer",
    companyName: "TechSupport Plus",
    experience: "1-3 years",
    location: "Noida, Uttar Pradesh",
    jobDescription: "Seeking a Technical Support Engineer to provide technical assistance to customers.",
    jobSkills: ["Troubleshooting", "Customer Service", "Linux", "Networking Basics", "Ticketing Systems"],
    numberOfOpenings: 4,
    workMode: "wfo",
    salary: "₹3,00,000 - ₹5,00,000 per year",
    datePosted: "2023-07-05"
  },
  {
    id: 22,
    jobTitle: "Blockchain Developer",
    companyName: "ChainTech India",
    experience: "3-5 years",
    location: "Bangalore, Karnataka",
    jobDescription: "Looking for a Blockchain Developer to build decentralized applications.",
    jobSkills: ["Solidity", "Ethereum", "Smart Contracts", "Web3.js", "Blockchain Architecture"],
    numberOfOpenings: 1,
    workMode: "remote",
    salary: "₹12,00,000 - ₹18,00,000 per year",
    datePosted: "2023-07-08"
  },
  {
    id: 23,
    jobTitle: "SEO Specialist",
    companyName: "SearchRank India",
    experience: "2-4 years",
    location: "Delhi",
    jobDescription: "We need an SEO Specialist to optimize websites and improve search rankings.",
    jobSkills: ["SEO", "Google Analytics", "Keyword Research", "On-page SEO", "Link Building"],
    numberOfOpenings: 2,
    workMode: "hybrid",
    salary: "₹4,00,000 - ₹7,00,000 per year",
    datePosted: "2023-07-10"
  },
  {
    id: 24,
    jobTitle: "Game Developer",
    companyName: "PlayStudio India",
    experience: "3-6 years",
    location: "Hyderabad, Telangana",
    jobDescription: "Looking for a Game Developer to create engaging mobile and PC games.",
    jobSkills: ["Unity", "C#", "Game Physics", "3D Modeling", "AR/VR"],
    numberOfOpenings: 2,
    workMode: "wfo",
    salary: "₹8,00,000 - ₹12,00,000 per year",
    datePosted: "2023-07-12"
  },
  {
    id: 25,
    jobTitle: "ERP Consultant",
    companyName: "EnterpriseSoft Solutions",
    experience: "5-8 years",
    location: "Mumbai, Maharashtra",
    jobDescription: "Seeking an ERP Consultant to implement and customize ERP solutions for clients.",
    jobSkills: ["SAP", "Oracle ERP", "Business Process", "Configuration", "Integration"],
    numberOfOpenings: 1,
    workMode: "hybrid",
    salary: "₹12,00,000 - ₹16,00,000 per year",
    datePosted: "2023-07-15"
  },
  {
    id: 26,
    jobTitle: "iOS Developer",
    companyName: "AppCrafter Studios",
    experience: "3-5 years",
    location: "Bangalore, Karnataka",
    jobDescription: "Looking for an iOS Developer to build and maintain iOS applications.",
    jobSkills: ["Swift", "iOS SDK", "Xcode", "UIKit", "Core Data"],
    numberOfOpenings: 2,
    workMode: "remote",
    salary: "₹9,00,000 - ₹13,00,000 per year",
    datePosted: "2023-07-18"
  },
  {
    id: 27,
    jobTitle: "Android Developer",
    companyName: "MobileFirst India",
    experience: "3-5 years",
    location: "Pune, Maharashtra",
    jobDescription: "We need an Android Developer to create innovative mobile applications.",
    jobSkills: ["Kotlin", "Android SDK", "Java", "Firebase", "Material Design"],
    numberOfOpenings: 2,
    workMode: "hybrid",
    salary: "₹8,00,000 - ₹12,00,000 per year",
    datePosted: "2023-07-20"
  },
  {
    id: 28,
    jobTitle: "Technical Writer",
    companyName: "DocuTech Solutions",
    experience: "2-4 years",
    location: "Chennai, Tamil Nadu",
    jobDescription: "Looking for a Technical Writer to create documentation for software products.",
    jobSkills: ["Technical Writing", "API Documentation", "Markdown", "Git", "Product Knowledge"],
    numberOfOpenings: 1,
    workMode: "remote",
    salary: "₹5,00,000 - ₹7,00,000 per year",
    datePosted: "2023-07-22"
  },
  {
    id: 29,
    jobTitle: "System Administrator",
    companyName: "SysManage India",
    experience: "4-6 years",
    location: "Gurgaon, Haryana",
    jobDescription: "Seeking a System Administrator to manage and maintain IT infrastructure.",
    jobSkills: ["Linux", "Windows Server", "Virtualization", "Shell Scripting", "Troubleshooting"],
    numberOfOpenings: 1,
    workMode: "wfo",
    salary: "₹8,00,000 - ₹11,00,000 per year",
    datePosted: "2023-07-25"
  },
  {
    id: 30,
    jobTitle: "Big Data Engineer",
    companyName: "DataMine Analytics",
    experience: "5-7 years",
    location: "Hyderabad, Telangana",
    jobDescription: "Looking for a Big Data Engineer to design and implement data processing systems.",
    jobSkills: ["Hadoop", "Spark", "Kafka", "Scala", "Data Pipelines"],
    numberOfOpenings: 1,
    workMode: "hybrid",
    salary: "₹14,00,000 - ₹18,00,000 per year",
    datePosted: "2023-07-28"
  },
  {
    id: 31,
    jobTitle: "Embedded Systems Engineer",
    companyName: "EmbedTech Solutions",
    experience: "3-6 years",
    location: "Bangalore, Karnataka",
    jobDescription: "We need an Embedded Systems Engineer to develop firmware for embedded devices.",
    jobSkills: ["C/C++", "RTOS", "Microcontrollers", "Device Drivers", "Debugging"],
    numberOfOpenings: 2,
    workMode: "wfo",
    salary: "₹9,00,000 - ₹13,00,000 per year",
    datePosted: "2023-08-01"
  },
  {
    id: 32,
    jobTitle: "Financial Analyst",
    companyName: "FinEdge Consulting",
    experience: "3-5 years",
    location: "Mumbai, Maharashtra",
    jobDescription: "Looking for a Financial Analyst to analyze financial data and prepare reports.",
    jobSkills: ["Financial Modeling", "Excel", "Accounting", "Forecasting", "Data Analysis"],
    numberOfOpenings: 2,
    workMode: "hybrid",
    salary: "₹7,00,000 - ₹10,00,000 per year",
    datePosted: "2023-08-03"
  },
  {
    id: 33,
    jobTitle: "Scrum Master",
    companyName: "AgileWorks India",
    experience: "5-7 years",
    location: "Pune, Maharashtra",
    jobDescription: "Seeking a Scrum Master to facilitate agile processes and remove impediments.",
    jobSkills: ["Scrum", "Agile", "JIRA", "Team Facilitation", "Continuous Improvement"],
    numberOfOpenings: 1,
    workMode: "wfo",
    salary: "₹12,00,000 - ₹16,00,000 per year",
    datePosted: "2023-08-05"
  },
  {
    id: 34,
    jobTitle: "UI Developer",
    companyName: "Frontend Labs",
    experience: "3-5 years",
    location: "Chennai, Tamil Nadu",
    jobDescription: "Looking for a UI Developer to create responsive and interactive web interfaces.",
    jobSkills: ["HTML5", "CSS3", "JavaScript", "TypeScript", "Angular"],
    numberOfOpenings: 2,
    workMode: "remote",
    salary: "₹7,00,000 - ₹10,00,000 per year",
    datePosted: "2023-08-08"
  },
  {
    id: 35,
    jobTitle: "Data Analyst",
    companyName: "InsightAnalytics",
    experience: "2-4 years",
    location: "Gurgaon, Haryana",
    jobDescription: "We need a Data Analyst to interpret data and provide actionable insights.",
    jobSkills: ["SQL", "Excel", "Power BI", "Data Visualization", "Statistics"],
    numberOfOpenings: 3,
    workMode: "hybrid",
    salary: "₹6,00,000 - ₹9,00,000 per year",
    datePosted: "2023-08-10"
  },
  {
    id: 36,
    jobTitle: "PHP Developer",
    companyName: "WebScript Solutions",
    experience: "3-5 years",
    location: "Noida, Uttar Pradesh",
    jobDescription: "Looking for a PHP Developer to build and maintain web applications.",
    jobSkills: ["PHP", "Laravel", "MySQL", "REST APIs", "JavaScript"],
    numberOfOpenings: 2,
    workMode: "wfo",
    salary: "₹6,00,000 - ₹9,00,000 per year",
    datePosted: "2023-08-12"
  },
  {
    id: 37,
    jobTitle: "Customer Success Manager",
    companyName: "ClientFirst Solutions",
    experience: "4-6 years",
    location: "Bangalore, Karnataka",
    jobDescription: "Seeking a Customer Success Manager to ensure client satisfaction and retention.",
    jobSkills: ["Account Management", "Customer Relations", "Upselling", "CRM", "Communication"],
    numberOfOpenings: 1,
    workMode: "hybrid",
    salary: "₹9,00,000 - ₹12,00,000 per year",
    datePosted: "2023-08-15"
  },
  {
    id: 38,
    jobTitle: "IT Project Manager",
    companyName: "ProManage IT Services",
    experience: "6-9 years",
    location: "Hyderabad, Telangana",
    jobDescription: "Looking for an IT Project Manager to oversee software development projects.",
    jobSkills: ["Project Management", "Agile", "Risk Management", "Budgeting", "Stakeholder Management"],
    numberOfOpenings: 1,
    workMode: "wfo",
    salary: "₹14,00,000 - ₹18,00,000 per year",
    datePosted: "2023-08-18"
  },
  {
    id: 39,
    jobTitle: "Cloud Engineer",
    companyName: "CloudScale Technologies",
    experience: "3-5 years",
    location: "Mumbai, Maharashtra",
    jobDescription: "We need a Cloud Engineer to deploy and manage cloud infrastructure.",
    jobSkills: ["AWS", "Azure", "Terraform", "CI/CD", "Cloud Security"],
    numberOfOpenings: 2,
    workMode: "remote",
    salary: "₹10,00,000 - ₹14,00,000 per year",
    datePosted: "2023-08-20"
  },
  {
    id: 40,
    jobTitle: "Graphic Designer",
    companyName: "CreativeMinds Studio",
    experience: "2-4 years",
    location: "Delhi",
    jobDescription: "Looking for a Graphic Designer to create visual content for digital and print media.",
    jobSkills: ["Adobe Photoshop", "Illustrator", "InDesign", "Branding", "Typography"],
    numberOfOpenings: 2,
    workMode: "hybrid",
    salary: "₹4,00,000 - ₹6,00,000 per year",
    datePosted: "2023-08-22"
  }
];